### ISSUE TITLE
Avoid global variables

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#13]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/62c4f6e3b51b6864e3e0457cb11f78cf762dd253/robot%20code/main.py#L11

It's generally a bad practice to keep shared state in global variables.

It's better to use function arguments to pass state between functions or to create classes that encapsulate the relevant variables.

**Comment by peeter-virk** [comment]
fixed issue in main file did not touch the global values in thresholding though

**Comment by ReikoR** [comment]
Using [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial) would be better without modifying the current code to much.  Variables defined in `if __name__ == '__main__':` still work as global variables in current code.

Example:
```python:
from functools import partial

def on_press(context, key):
    running, state, manual_inputs = context
    
if __name__ == '__main__':
    listener = keyboard.Listener(
        on_press=partial(on_press, (running, state, manual_inputs)),
        on_release=partial(on_release, (running, state, manual_inputs)),
        suppressed=True
    )
```

**Comment by Kuulike** [comment]
implemented the suggestion

**Comment by ReikoR** [comment]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/c034face25eb45327026c3c1f7eee63f54f79fc2/robot%20code/Thresholding.py#L26-L32

`Trackbar_values` can be passed as an argument to `savefile` function, instead of using `global`.

**Comment by Kuulike** [comment]
suggestion implemented
