### ISSUE TITLE
Replace repeating code with loops

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#14]
One example:
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/62c4f6e3b51b6864e3e0457cb11f78cf762dd253/robot%20code/main.py#L48-L61

**Comment by ReikoR** [comment]
There's also some code repetition in `Thresholding.py`:
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/7cae8a31e7d31004acf5ce9fa8edfdef956656e9/robot%20code/Thresholding.py#L57-L94

**Comment by Kuulike** [comment]
The python application for the createtrackbar function can not pass any extra arguments to the update function except for the new value of the variable. http://www.opencv.org.cn/opencvdoc/2.3.2/html/modules/highgui/doc/user_interface.html#createtrackbar

**Comment by ReikoR** [comment]
[functools.partial](https://docs.python.org/3/library/functools.html#functools.partial) can be used to bind values to trackbar `onChange` function.

Trackbar properties can be kept in arrays.

Some of the code for an example:
```python
from functools import partial

trackbar_names = ["H", "S", "V", "hH", "hS", "hV", "Mode(0-green, 1-black, 2-white, 3-pink, 4-blue)"]
trackbar_counts = [179, 255, 255, 179, 255, 255, 5]
trackbar_values = [29, 24, 69, 74, 151, 193, 4]

def update_value(value_index, new_value):
    trackbar_values[value_index] = new_value
    
for index, name in enumerate(trackbar_names):
    cv2.createTrackbar(
        name, 
        "Trackbars", 
        trackbar_values[index], 
        trackbar_counts[index],
        partial(update_value, index)
    )
```

**Comment by Kuulike** [comment]
idea integrated and tested
