### ISSUE TITLE
Use enums instead of arbitrary values

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#15]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/62c4f6e3b51b6864e3e0457cb11f78cf762dd253/robot%20code/main.py#L23

Using constants defined with [enums](https://docs.python.org/3/library/enum.html) help make code more readable and harder to make errors in code.

**Comment by peeter-virk** [comment]
now using enums for state

**Comment by ReikoR** [comment]
Using `IntEnum` is probably better.
```python
from enum import IntEnum

class State(IntEnum):
    stopped = 0
    automatic = 1
    remote = 2
```

Creating shared value:
```python
state = mp.Value('i', State.automatic)
```

Comparisons:
```python
def on_press(context, key):
    elif state.value == State.remote:
```

There shouldn't be any need for `._value_`

**Comment by Kuulike** [comment]
removed all ._value_ calls associated with IntEnums

**Comment by ReikoR** [comment]
`._value_` is still used here:
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/f928aeb4cd5ac96405098a886fadbd8b1d98b824/robot%20code/main.py#L54

If value is actually needed, then enum's `.value` should be used instead of `._value_`. 

Class variables starting with underscore should be considered protected and not used outside the class.

More info:
https://www.tutorialsteacher.com/python/public-private-protected-modifiers

**Comment by peeter-virk** [comment]
lahendatud
