### ISSUE TITLE
Use serial.tools.list_ports

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#16]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/62c4f6e3b51b6864e3e0457cb11f78cf762dd253/robot%20code/movement_controller.py#L29-L35

Instead of blindly trying to open ports, use [serial.tools.list_ports](https://pyserial.readthedocs.io/en/latest/tools.html) to find the correct port based on the port info.

**Comment by peeter-virk** [comment]
now using serial.tools.list_ports to connect to the board
