### ISSUE TITLE
Use unpacking operator

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#17]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/62c4f6e3b51b6864e3e0457cb11f78cf762dd253/robot%20code/movement_controller.py#L8-L9

Instead of creating a function for unpacking, use unpacking operator.
https://docs.python.org/3/tutorial/controlflow.html#tut-unpacking-arguments

**Comment by peeter-virk** [comment]
now using unpacking operator

**Comment by ReikoR** [comment]
There shouldn't be any need for `send_ms` function. It can be removed and any usages of it could be replaced with direct calls to `send_motorspeeds` function.

Also this:
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/7cae8a31e7d31004acf5ce9fa8edfdef956656e9/robot%20code/movement_controller.py#L79

Could be replaced with slightly simpler code:
```python
ms = send_motorspeeds(ser, *speeds, target_speeds[3])
```

Also `speeds` variable is not defined when `state.value` is not equeal to 1 or 2:
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/7cae8a31e7d31004acf5ce9fa8edfdef956656e9/robot%20code/movement_controller.py#L61-L62

**Comment by peeter-virk** [comment]
removed all traces of send_ms
