### ISSUE TITLE
Use map()

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#19]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/62c4f6e3b51b6864e3e0457cb11f78cf762dd253/robot%20code/movement_logic.py#L23

Use map function to create list from another list and avoid repeating the code.

https://www.programiz.com/python-programming/methods/built-in/map

**Comment by ReikoR** [comment]
Better way to write it would be to use lambda:

```python
import math


WHEEL_ANGLES = [210, 330, 90]


def linear_velocity(speed, angle, wheel_angle):
    return int(speed * math.cos(math.radians(angle) - math.radians(wheel_angle)))


def move_omni(speed, angle):
    return list(map(lambda wheel_angle: linear_velocity(speed, angle, wheel_angle), WHEEL_ANGLES)) + [0]
```

Or even better, using list comprehension:

```python
def move_omni(speed, angle):
    return [linear_velocity(speed, angle, wheel_angle) for wheel_angle in WHEEL_ANGLES] + [0]
```

**Comment by peeter-virk** [comment]
now using list comprehention

**Comment by ReikoR** [comment]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/ae68499f38be2f319db8e3297896aeec4e0ce4d2/robot%20code/game_logic.py#L19-L20

It would be clearer what the code does, if separate arguments are used instead of an array:
```python
def linear_velocity(speed, angle, wheel_angle):
    return int(speed * math.cos(math.radians(angle) - math.radians(wheel_angle)))
```

**Comment by peeter-virk** [comment]
fixed
