### ISSUE TITLE
Simplify omni-movement code

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#20]
Separate `rotate_omni` function should not be needed. Rotation speed could be an argument of `move_omni` function and added to each wheel speed.

`combine_moves` should also not be needed. In `manual_control.py`, movement speed and angle could be calculated based on the button presses and used as a argument for `move_omni` function. Other uses of `combine_moves` should also be unnecessary when rotation speed is added as an argument to `move_omni` function.

**Comment by peeter-virk** [comment]
Change is not worth the time and effort it would take to modify large parts of the current code as well as having to fix all of the potential bugs related to refactoring.
