### ISSUE TITLE
Change the way arrays are created

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#23]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/7cae8a31e7d31004acf5ce9fa8edfdef956656e9/robot%20code/Camera.py#L124-L126

There are better ways to create arrays.

For example:
```python
import numpy as np

MAX_KEYPOINT_COUNT = 11

# with list comprehension
x = [0 for i in range(0, MAX_KEYPOINT_COUNT)]

# or with numpy
y = np.zeros(MAX_KEYPOINT_COUNT, dtype=int)
```

**Comment by Kuulike** [comment]
addressed it in code
