### ISSUE TITLE
[Mechanics] - motor holder design tweaks

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#24]
2 enhancements:
1. Reduce the radius of the holder, this makes creating it faster and wastes less material
2. Put the shaft fastening hole between the wheel fastening holes. This way there can be no interference bewteen the two fasteners

![image](https://user-images.githubusercontent.com/5435954/140619116-dfb52c54-4004-47ce-9c44-313064c6f924.png)

**Comment by priitro** [comment]
1. Reduced motor holder radius to 28 mm. 
2. Positioned holes around, and now interference will be between two different fasteners.
![image](https://user-images.githubusercontent.com/73076712/140621208-9f63aebc-2b5a-4962-9de8-a8510954db7c.png)
Motor holder sketch 
![image](https://user-images.githubusercontent.com/73076712/140621231-f39ef209-2916-42db-b969-c4930a82ebef.png)

**Comment by Akustav** [comment]
Maybe we can make it 25? Then we can use 25mm materials

**Comment by priitro** [comment]
Its is possible now - diameter is 25 mm and 2 mm from edge of hole to perimeter
![image](https://user-images.githubusercontent.com/73076712/140624691-134d9573-5205-4ecf-a492-3ec46a03000a.png)

**Comment by Akustav** [comment]
Seems ok now
