### ISSUE TITLE
[Mechanics] - sketch has underdefined elements

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#25]
Check that sketches have no underdefined elements, so they need to be black, not blue:

![image](https://user-images.githubusercontent.com/5435954/140619216-b9cd5b1a-bfc7-4830-880c-5223e53b1280.png)

**Comment by priitro** [comment]
Changed holes position and defined whit constraints  sketch. 
![image](https://user-images.githubusercontent.com/73076712/140620997-005e8c25-f599-4014-96c5-3b87e4ac5977.png)

**Comment by Akustav** [comment]
Seems OK now
