### ISSUE TITLE
[Mechanics] - wheel could damage field elements or robots

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#26]
When the wheel is spinning it could damage parts of the fields (baskets) or robots it hits with bolt heads. You you plan to cover the wheels? 

I not maybe recessed screws are better.

![image](https://user-images.githubusercontent.com/5435954/140646214-710b6ec1-d53f-4bc5-9962-603e935bf4da.png)

**Comment by priitro** [comment]
1.I have designed wheel cover. I (we - others don't now yet about it ) haven't decided yet use it or not. If we use cover we can use same screws, if not i can change screws type and redesign holes. 
![image](https://user-images.githubusercontent.com/73076712/140657497-4ffcd64a-ccb0-47a1-9279-b1c036a6ed0d.png)
![image](https://user-images.githubusercontent.com/73076712/140657519-1c4277fb-5535-4dc2-9dc9-b90bedaa17b7.png)

2. Bottom plate design is`'t ready yet and i don't know whether we use protective edge or not. Right now i have placed motors and wheels to bottom plate and we may have space for edge on it.
![image](https://user-images.githubusercontent.com/73076712/140657664-91853807-8b21-4c96-a5d8-374a3b472316.png)

**Comment by Akustav** [comment]
Okay, Seems like you have considered it. Will close

**Comment by priitro** [comment]
I redesigned holes - now I can use both screws depending of whether I use cower or not:  Design of screw may be bad but it gives idea I mean.
![image](https://user-images.githubusercontent.com/73076712/140659308-19634d36-79fa-4eb7-a6d7-cf2d4f515f88.png)
