### ISSUE TITLE
Wrong motor driver package

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#33]
HVSSOP (28) package is used, but the available drivers are in VQFN-HR (14) package.

Package is also specified in the guide:
https://reikor.github.io/picr21-basketball-robot-guide/electronics/components.html#_motor_driver

**Comment by JoelJaemaa** [comment]
New footprint has no thermal pad under it, I will draw that in manually

**Comment by ReikoR** [comment]
Still wrong footprint and symbol.

Recommended (available in the lab) component:
https://reikor.github.io/picr21-basketball-robot-guide/electronics/components.html#_motor_driver
>DRV8243
>Product code: PDRV8243HRXYQ1 (HW variant)
>Package: VQFN-HR (14)

From the datasheet:
![image](https://user-images.githubusercontent.com/1595938/144699902-07a3ac58-83f3-4e89-b162-48b8e2e4040e.png)

**Comment by ReikoR** [comment]
It probably doesn't matter too much, but it would be nice to keep minimum solder mask expansion.

![image](https://user-images.githubusercontent.com/1595938/145261762-706b7613-0354-4483-9f3e-c7ed793b6b2c.png)

JLCPCB specifies the minimum at 0.05 mm.
https://jlcpcb.com/capabilities/Capabilities

![image](https://user-images.githubusercontent.com/1595938/145261677-5509af53-a745-4a38-8482-647ebe2413ac.png)


[Datasheet ](https://www.ti.com/lit/ds/symlink/drv8243-q1.pdf) recommends 0.05 mm.

![image](https://user-images.githubusercontent.com/1595938/145261942-5f2bcafb-0c59-4b8f-b839-84c4b914453a.png)

**Comment by JoelJaemaa** [comment]
I can't seem to find this in the rules. There is a rule in design rules -> mask -> solder mask expansion -> expansion top and it's set at 4 mil.

**Comment by ReikoR** [comment]
For this component it's defined on the component footprint. Component library needs to be changed.
