### ISSUE TITLE
Incorrect microcontroller pins used

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#34]
USB and programmer signals can be connected only to specific pins. PWM output and encoder input signals can also be connected to limited amount of pins.

Recommended way for finding correct pins is to use Pinout & Configuration view in STM32CubeIDE.

More information can be found on the firmware page in the guide:
https://reikor.github.io/picr21-basketball-robot-guide/electronics/firmware.html

**Comment by JoelJaemaa** [comment]
Updated the pins. Let me know if these are okay now

**Comment by ReikoR** [comment]
Servo needs a separate timer as it needs different PWM frequency from motors and thrower. PB0 pin does not have any usable timer currently.
![image](https://user-images.githubusercontent.com/1595938/144700485-d3ef2165-fa02-4fb5-bf01-523dca8d4157.png)
![image](https://user-images.githubusercontent.com/1595938/144700427-8eb64d86-a598-418f-9e36-0c00687b2e0b.png)

What interface is accelerometer using? I2C? PA5 and PA10 pins are not connected to anything usable in the MCU.
![image](https://user-images.githubusercontent.com/1595938/144700683-0bcaed37-08a1-4b02-adb0-8503da22515e.png)
