### ISSUE TITLE
Analog signal can't go through digital isolator

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#35]
MAX14930 is a digital isolator and the outputs are either low or high.
Some other solution would be needed for measuring voltages on the other side of an isolator.

What is the purpose of measuring battery voltage?

**Comment by JoelJaemaa** [comment]
Peeter wanted the ability to measure battery voltage so that we can compensate for speed as the battery voltage drops

**Comment by ReikoR** [comment]
Compensate for wheel speeds or thrower speeds?

Wheel motors have encoders for closed loop speed control and voltage regulator can be used to keep the thrower motor controller voltage constant.
