### ISSUE TITLE
Use 0603 package for resistors and smaller capacitors

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#36]
Most of the passive components in the lab are in 0603 package but some components on the schematic are in 0805 package. It doesn't make sense to order new components if the components with same values are available. For higher capacitances it's ok to use larger packages, but it's better to check what's already available in the lab.

**Comment by JoelJaemaa** [comment]
Changed 0805 footprints to 0603

**Comment by ReikoR** [comment]
There are still components in 0805 package.

![image](https://user-images.githubusercontent.com/1595938/144700963-84a55f2c-c898-440e-be44-1195439ed9b1.png)
![image](https://user-images.githubusercontent.com/1595938/144700967-c27cdbfb-de46-428c-8ac2-4cb4c25c9c03.png)
![image](https://user-images.githubusercontent.com/1595938/144700978-11f95837-ae62-4d33-af2d-82eaffb77ae7.png)
![image](https://user-images.githubusercontent.com/1595938/144700983-58dd384b-bee6-4305-99bc-49d09426909b.png)
![image](https://user-images.githubusercontent.com/1595938/144700998-8205839a-08ea-4050-adc7-b6d32a69db58.png)
![image](https://user-images.githubusercontent.com/1595938/144701009-363cf189-d820-43c6-8605-4ef2d8bba39f.png)

**Comment by JoelJaemaa** [comment]
Fixed
