### ISSUE TITLE
NCV8730ASN500T1G does not have PG

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#37]
![image](https://user-images.githubusercontent.com/1595938/143296703-399a3f20-15ff-45fb-b5de-80d717138e2d.png)

From the [datasheet](https://www.onsemi.com/pdf/datasheet/ncv8730-d.pdf):

![image](https://user-images.githubusercontent.com/1595938/143297095-41ad2a95-f5e9-4b81-a036-55102dd9614f.png)

**Comment by JoelJaemaa** [comment]
Removed the LED and resistor atttached to the PG pin and connected them to +5v motor rail and GND instead for checking if we have the voltage.
