### ISSUE TITLE
Use cheaper and simpler connector for GPIO

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#38]
![image](https://user-images.githubusercontent.com/1595938/143297872-e53450e4-0190-4f06-9e87-5c95a7aeb395.png)

Programmer connector is not very cheap. It has 1.27 mm pitch and is keyed, requiring matching connector to be used.

![image](https://user-images.githubusercontent.com/1595938/143298511-8ef9bfcd-e4ee-43e5-b6e8-e44bc0e45705.png)

We have pin headers in the lab with 1.27, 2.0 and 2.54 mm pitch and also micromatch connectors with different pin counts.
If really needed, then we can order something else.

**Comment by JoelJaemaa** [comment]
Replaced with micromatch 4 connectors for individual addon features
