### ISSUE TITLE
Select correct resistors for DRV8243 configuration pins

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#40]
Some pins can be connected directly to GND, left unconnected or connected with specific resistor to GND.

For example currently ITRIP pin is connected to GND with a 0 Ohm resistor, which results in output current not being limited. I would recommended current limit of around 2 to 3 A. Current limit can be set with resistors connected to ITRIP and IPROPI pins.

![image](https://user-images.githubusercontent.com/1595938/143300433-320a4470-c1c6-447b-be36-1540b8193063.png)
![image](https://user-images.githubusercontent.com/1595938/143300494-0777e404-edbd-4e50-9d30-15a0a637a36e.png)

Relevant information can be found from the datasheet:
https://www.ti.com/lit/ds/symlink/drv8243-q1.pdf

Let me know if more help is needed.

**Comment by JoelJaemaa** [comment]
The resistors in the schematic are currently just placeholders so they could be placed on the pcb. I will update them soon.

**Comment by JoelJaemaa** [comment]
Changed ITRIP resistor to 47K. Does that seem okay? Rest of them should be fine at 0 ohm (GND)?

**Comment by ReikoR** [comment]
Resistor values should be fine, but place the resistor better on the schematic. Currently it's a bit hard to understand which is which.  It would be better to place resistors vertically.

![image](https://user-images.githubusercontent.com/1595938/149468403-316bfc50-544e-488b-90bf-eb28273d0fdf.png)

**Comment by JoelJaemaa** [comment]
Resistor placement fixed. Made other schematic elements nicer as well. Changed the values of feedback resistors in the switching regulator with values that were available in the lab. Same ratio. 5V is nice and stabile.
