### ISSUE TITLE
Refactor min max limiting into separate function

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#44]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/f928aeb4cd5ac96405098a886fadbd8b1d98b824/robot%20code/game_logic.py#L124-L126

**Comment by peeter-virk** [comment]
done

**Comment by ReikoR** [comment]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/8d38ac2402675cea33a5d87779682db3a0426ee8/robot%20code/game_logic.py#L36-L37

Current `minimax` function won't work, because it uses the same names for arguments as built-in functions `min` and `max`.

**Comment by peeter-virk** [comment]
Fixed in main
