### ISSUE TITLE
Duplicate camera code

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#45]
`Camera.py` and `Thresholding.py` contain duplicate camera code.

It would be better to have separate Camera class that can be used for getting frames for regular image processing and thresholding.

**Comment by Kuulike** [comment]
moved the thresholding tool into the testing code package

**Comment by ReikoR** [comment]
Is the code in `Thresholding.py` not used any more?

Camera code should be in  separate file/class so it can be used by both thresholding and main robot code without duplicating it.

**Comment by peeter-virk** [comment]
files have been merged

**Comment by ReikoR** [comment]
Putting everything in the same file is not the best solution, but better than before.
