### ISSUE TITLE
Add decoupling capacitor to VDDA

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#47]
Each VDD/VDDA pin should have separate 100nF capacitor.

![image](https://user-images.githubusercontent.com/1595938/144701339-0fc11d3d-4ccd-43c7-b29d-55609f9a072a.png)

**Comment by JoelJaemaa** [comment]
I placed them near the pins on the PCB. I can correct it in the schematic as well.

**Comment by ReikoR** [comment]
There should be additional 100nF capacitor, so that each VDD/VDDA pin would have one.
