### ISSUE TITLE
Wrong package for isolators

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#48]
![image](https://user-images.githubusercontent.com/1595938/144701528-3ff17c8e-e8ec-4f9f-82fb-8e30218e6680.png)

MAX14930DASE+ isolators are in narrow SOIC package. Wide SOIC package is currently used in the design.

**Comment by JoelJaemaa** [comment]
Okay, will fix it

**Comment by JoelJaemaa** [comment]
Fixed
