### ISSUE TITLE
Incorrect BUK6Y10-30P symbol

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#49]
Symbol has 2 extra pins floating around. 

![image](https://user-images.githubusercontent.com/1595938/144701706-8efc6c84-fa17-40ad-8bb4-60be7cc9e77e.png)

Only 3 signals are connected to the footprint.

![image](https://user-images.githubusercontent.com/1595938/144701738-bc3456c9-5f41-46ec-87b5-7c4ac592d2b8.png)

In the case where 1 pin connects to multiple pads it's better to use letters as designators instead of numbers:

![image](https://user-images.githubusercontent.com/1595938/144701770-6bd368e0-fa85-4f98-a52b-1592c7d5d104.png)
![image](https://user-images.githubusercontent.com/1595938/144701805-732eaf87-8445-4c85-9d64-3669a14d6217.png)

D - drain
S - source
G - gate

Designators with the same name will be connected together. This way the symbol only needs 3 pins.

**Comment by JoelJaemaa** [comment]
Fixed it
