### ISSUE TITLE
Use switching regulator for servo power

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#53]
Linear regulators waste a lot of power when currents are high and voltage difference is big.

**Comment by JoelJaemaa** [comment]
Okay, I'll look into it but that linear regulator should work okay for now. It will dissipate more heat but it has a small load and the batteries should be able to handle it. If I have time I will replace it on monday but if not then can we keep it this way? I have the part, no need to order it.

**Comment by ReikoR** [comment]
Some recommendations:

1. You can use Texas Instruments Webench to generate the design for the regulator:
https://www.ti.com/design-resources/design-tools-simulation/webench-power-designer.html
Other manufacturers have similar tools available.

2. Check that the regulator is in stock:
https://www.mouser.ee/c/power/power-management-ics/voltage-regulators-switching-regulators/?m=Texas%20Instruments&number%20of%20outputs=1%20Output&topology=Buck&instock=y
There are also some regulators in the lab from last year.

It's not that the batteries are not able to handle it. Linear regulators waste a lot of power. The load from servo is not that small.

**Comment by JoelJaemaa** [comment]
Okay. I'll do this tonight.

**Comment by JoelJaemaa** [comment]
I'll come by the lab tomorrow and check what we have. Everything the TI Webench recommended is out of stock or on order. I know that a linear regulator is not a good option but I put it in initially because it's what I have. I also do stuff for Estcube so I'll check if we have anything in stock there that I could get. Other than moving stuff from M1 layer and this regulator issue, everything else should be better now.

**Comment by ReikoR** [comment]
I ordered these regulators:
https://www.ti.com/product/TPS62933

You can use those or the ones you find in the lab.

I'll probably order these inductors also:
https://ee.farnell.com/bourns/srp6060fa-5r6m/inductor-shld-5-6uh-10a-aec-q200/dp/2901832?st=2901832

**Comment by JoelJaemaa** [comment]
Found a couple TPS54227s in the lab. Will use those. I did not check what size inductors we have though.

**Comment by JoelJaemaa** [comment]
Schematics and board have been updated with TPS54227 based buck converter

**Comment by ReikoR** [comment]
1. Vias in TPS54227 footprint are not connected to GNDB.

![image](https://user-images.githubusercontent.com/1595938/146239012-2a78b41b-6712-440d-84b9-45a732f31e1f.png)

Footprint has pad 9, but symbol does not have pin 9, so the pad is not connected to anything.

Also it's better to add vias in PCB design not in component footprint. Then it's easier to change via sizes and locations.

2. Inductor used right now is in 1206 (3216 metric) size. I don't think there are any inductors in that size that can meet the recommended specs. TI Webench recommends: L: 4.7 μH - 7.05 μH, DCR: 125 mΩ (max), IDC: 3.64 A (min).

3. More input capacitance should be used. Current values are below the recommendations. It's probably better to use higher capacitance than recommended, because the servo motor could have high peak current draw.

**Comment by JoelJaemaa** [comment]
I'd like to change it but this is a downloaded library and not one that I made. So the vias are already there. I'd like to remove the vias and add pin 9. Also edit the other footprints to move stuff around between mechanical layers. How can I do that?

I added more capacitance to the input.

**Comment by ReikoR** [comment]
You can open the existing library files and modify them or you can create a new library yourself. It's easy to create components with Tools -> IPC Compliant Footprint Wizard.

**Comment by JoelJaemaa** [comment]
Pin 9 GNDB issue fiexd

**Comment by JoelJaemaa** [comment]
Proper inductor also used now

**Comment by ReikoR** [comment]
1. Which exact inductor are you using in the design? Footprint in the design is for Würth Elektronik 744777930, but that one is not suitable. Würth has 4.7 uF inductors in similar package.

2. Move inductor closer to regulator.

Recommendation from [TPS54227 datasheet](https://www.ti.com/lit/ds/symlink/tps54227.pdf):

> 2\. Keep the SW node as physically small and short as possible to minimize parasitic capacitance and
inductance and to minimize radiated emissions. Kelvin connections should be brought from the output to the
feedback pin of the device.

![image](https://user-images.githubusercontent.com/1595938/147444301-4352f1ad-b9ec-4966-951d-c951b363e994.png)

3. Avoid routing anything below the inductor.

![image](https://user-images.githubusercontent.com/1595938/147444575-839d51a1-daee-4d4d-8719-d727912010dc.png)

4. Output capacitance is still below the recommendations.

From TI Webench:

Cin = 20uF (2x 10uF)
Cout = 44uF (2x 22uF)

![image](https://user-images.githubusercontent.com/1595938/147444824-11d4a0e5-10c8-43d1-8767-a21c4eaed5ae.png)
![image](https://user-images.githubusercontent.com/1595938/147444835-8bec58ec-4815-4a33-b462-78089470e0f0.png)

**Comment by JoelJaemaa** [comment]
Using a 4.7uH inductor I found in the lab. Has the same footprint. Using this Würth part for the footprint.

**Comment by JoelJaemaa** [comment]
Added more capacitance and shortened L1 path.

**Comment by JoelJaemaa** [comment]
All issues should be fixed now

**Comment by ReikoR** [comment]
This has not been fixed:

3\. Avoid routing anything below the inductor.

![image](https://user-images.githubusercontent.com/1595938/147444575-839d51a1-daee-4d4d-8719-d727912010dc.png)

**Comment by JoelJaemaa** [comment]
Fixed

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/147876008-67ec18a9-7e3a-43ee-bba0-954ff9cdbeb5.png)

Linear regulator is not needed anymore, since the switching regulator can provide the 5V supply.

**Comment by JoelJaemaa** [comment]
Removed it and put all the battery side 5V stuff onto the switching regulator

**Comment by ReikoR** [comment]
Vias in TPS54227 footprint are again not connected to GNDB. It's better to remove vias from footprint and add them in PCB design.

![image](https://user-images.githubusercontent.com/1595938/146239012-2a78b41b-6712-440d-84b9-45a732f31e1f.png)

**Comment by JoelJaemaa** [comment]
Yeah it does not like to stay connected. Removed them from footprint and added manually. Should be fixed now.
