### ISSUE TITLE
Connect decoupling capacitors as close as possible to the components

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#57]
![image](https://user-images.githubusercontent.com/1595938/145268562-b13a15d5-68ab-4df6-8648-54484100b0b2.png)

Track inductance should be minimized by keeping them as short as possible, otherwise decoupling capacitors won't be as effective.

**Comment by JoelJaemaa** [comment]
Fixed

**Comment by ReikoR** [comment]
Capacitors need to be much closer.

![image](https://user-images.githubusercontent.com/1595938/145704741-af44a4d7-9623-448f-9f57-1368fb1e21cb.png)

**Comment by JoelJaemaa** [comment]
Fixed

**Comment by ReikoR** [comment]
Decoupling capacitors for motor driver VM pins could be be closer to the drivers by putting capacitors to bottom layer and connecting them with vias.

![image](https://user-images.githubusercontent.com/1595938/146250201-a300b40b-e39a-431f-812b-e6d121e2339b.png)

**Comment by JoelJaemaa** [comment]
Fixed. Also added an extra 4.7uf cap there. Moved both to bottom.
