### ISSUE TITLE
Avoid routing ground

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#60]
![image](https://user-images.githubusercontent.com/1595938/145270099-d054913e-634a-49d8-af47-2afef53c4682.png)

Ground should be connected to internal ground layer(s) with vias as close as possible to component pads.

**Comment by JoelJaemaa** [comment]
Fixed

**Comment by ReikoR** [comment]
Vias should be as close as possible to pads to reduce inductance from tracks.

![image](https://user-images.githubusercontent.com/1595938/145704997-dd260761-b029-434a-ac86-837bf68f2872.png)

**Comment by JoelJaemaa** [comment]
Fixed the long grounds

**Comment by ReikoR** [comment]
This via could still be closer:
![image](https://user-images.githubusercontent.com/1595938/146249167-4c91ebd0-6857-4073-83de-edec4c81d646.png)

Why are you using the default via size everywhere? Vias can be smaller and moved closer to the pads.

Design rule for via sizes can be changed:
![image](https://user-images.githubusercontent.com/1595938/146249461-bdd24bda-08dd-4a85-9039-752f1712c08d.png)

**Comment by JoelJaemaa** [comment]
Used a smaller via and placed it closer. 
I'm using default size because I did not necessarily need to use any other size before.
