### ISSUE TITLE
Use wider tracks or polygons for higher currents

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#61]
![image](https://user-images.githubusercontent.com/1595938/145270485-75d2c87d-4f16-4f1b-aed6-bef660f5d2c6.png)

**Comment by JoelJaemaa** [comment]
I tried making some improvements. Hopefully it should be a bit better now.

**Comment by ReikoR** [comment]
It's better, but you should move the tracks a bit and use smaller vias (at least for signals) to make power tracks for drivers wider. 

Driver's VM capacitors should also be as close to the driver as possible. SMD capacitors can also be on the bottom of the board and connected with vias.

![image](https://user-images.githubusercontent.com/1595938/145705230-292c666d-6ad1-450f-9cdb-1d11fb43ebb8.png)

**Comment by JoelJaemaa** [comment]
Will do it tonight

**Comment by JoelJaemaa** [comment]
I managed to get the caps a bit closer and unchecked the option that removes loops from traces. This allowed me to get more vias on one trace and get the motor driver power connections connected from both sides.
