### ISSUE TITLE
Board outline should be drawn on Mechanical 1 (M1) layer

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#62]
Currently it's on top layer, which is for top layer copper.

There are some other things on M1 layer, which should be moved to some other layers.

![image](https://user-images.githubusercontent.com/1595938/145271305-e50dfa61-47e4-45cf-b6e3-6adad484c0da.png)

Component bodies are typically placed on M13 (Top 3D Body) or M14 (Bottom 3D Body) layers.

**Comment by JoelJaemaa** [comment]
Moved outline to M1. Can't move other stuff on M1 to M13 or M14. It only lets me choose top, bottom or the two middle GND layers. Can I move them to one of these?

**Comment by ReikoR** [comment]
Other stuff needs to be moved in component libraries.

**Comment by JoelJaemaa** [comment]
Will fix tonight

**Comment by JoelJaemaa** [comment]
I moved the stuff in libraries but it does not seem to update on the PCB. Even after deleting and re-adding the component. Can you help me with this, please? Otherwise it should all be done. Regulator stuff is fixed as well now.

**Comment by ReikoR** [comment]
You probably need to use **Tools -> Update From PCB Libraries...** to update the footprints.

**Comment by JoelJaemaa** [comment]
Should be fixed now
