### ISSUE TITLE
Board could be smaller

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#63]
Preferred size is 50 x 50 mm or smaller, because this size is cheaper.

**Comment by JoelJaemaa** [comment]
Unfortunately I don't have time to do that. I'll pay the difference from my own pocket if need be.

**Comment by ReikoR** [comment]
University courses don't work like that.

Current board could clearly be smaller, even if it does not fit into 50 x 50 mm size.

**Comment by JoelJaemaa** [comment]
Okay, I'll try to make it a bit smaller but I'm afraid I don't have time to re-design it too much.

**Comment by JoelJaemaa** [comment]
I managed to make the board a bit smaller. Not a lot but at least a bit.
