### ISSUE TITLE
Elif not being used

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#65]
Some places where `elif`` should be used:

https://github.com/ut-robotics/picr21-team-tlo-rock/blob/8d38ac2402675cea33a5d87779682db3a0426ee8/robot%20code/game_logic.py#L101-L104

https://github.com/ut-robotics/picr21-team-tlo-rock/blob/8d38ac2402675cea33a5d87779682db3a0426ee8/robot%20code/game_logic.py#L176-L183

**Comment by peeter-virk** [comment]
Fixed in main

**Comment by ReikoR** [comment]
This code can also use elif:
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/b54554c1068070ccf952da579a595b7e8e827c08/robot%20code/game_logic.py#L105-L108

**Comment by peeter-virk** [comment]
fixed
