### ISSUE TITLE
Avoid overlapping schematic objects

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#66]
![image](https://user-images.githubusercontent.com/1595938/145705461-81620aea-25a0-4a50-afc8-3ac5f9293bc1.png)

![image](https://user-images.githubusercontent.com/1595938/145705483-4caccca0-1a8d-4a58-aebf-f97ef989a55b.png)

**Comment by JoelJaemaa** [comment]
Fixed
