### ISSUE TITLE
Un-routed nets

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#67]
![image](https://user-images.githubusercontent.com/1595938/145705518-c999b87e-fbcf-416b-8f2a-9da40be76cfd.png)

Use Tools -> Design Rules Check... to find problems in the PCB design.

![image](https://user-images.githubusercontent.com/1595938/145705543-78388582-e3f7-4be7-b40b-4f165253d3c1.png)

**Comment by JoelJaemaa** [comment]
Fixed
