### ISSUE TITLE
Button handling with manual control not separated

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#68]
You have similar code on these functions:

https://github.com/ut-robotics/picr21-team-tlo-rock/blob/b54554c1068070ccf952da579a595b7e8e827c08/robot%20code/main.py#L15-L16

https://github.com/ut-robotics/picr21-team-tlo-rock/blob/b54554c1068070ccf952da579a595b7e8e827c08/robot%20code/main.py#L29-L30

Additionally I am not sure why you need a separate press and release handler. To control the robot manually and toggle the button on and off? It seems weird to me that you do this manual control in the main loop. Maybe have it as a separate state and handle it in the game logic or have a separate parallel module.

**Comment by peeter-virk** [comment]
This is not an issue, simply a design choice to ensure the robot would know whether the key is pressed down or not.
