### ISSUE TITLE
Depth frame not aligned

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#69]
You currently do not align the depth frame to the color one. This can result in wrong distance readings.

https://github.com/ut-robotics/picr21-team-tlo-rock/blob/b54554c1068070ccf952da579a595b7e8e827c08/robot%20code/Camera.py#L139-L143

An example:
https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/align-depth2color.py

**Comment by peeter-virk** [comment]
added aligning to depth frames
