### ISSUE TITLE
[Mechanics] - wrong use of fillet

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#7]
You most likely want to use chamfer, not fillet here. Screw heads themselves are conical in shape:
![image](https://user-images.githubusercontent.com/5435954/136435246-e7e0bade-1e3e-4748-90b9-f8a3d0b17286.png)

**Comment by priitro** [comment]
Yes, its basically hack. I made all holes from sketch side from origin wall, not from mirror.  After placing all spacers between upper an bottom plate I found that one spacer situated in same line with motor attachment bolt.  Editing hole feature wasn't so easy to solve. I must use countersink  shape head bolt in there. As I understood from Martin we have to drill there countersink holes  by my self. I will try to solve it.
