### ISSUE TITLE
Check and fix design rule errors

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#72]
For example in current design:

![image](https://user-images.githubusercontent.com/1595938/146250932-80420c8e-9ff7-411b-8582-816e78d99fcb.png)

**Comment by JoelJaemaa** [comment]
That was an accidental reduntant trace from moving stuff. Will look over them and fix.

**Comment by ReikoR** [comment]
1. **Short-Circuit Constraint Violation** and **Hole To Hole Clearance Constraint Violation**

Remove holes inside the slots in USB connector footprint. These are not needed.

![image](https://user-images.githubusercontent.com/1595938/147850328-f6752e85-6687-44a9-a695-193b002cf0d5.png)

2. **Hole Size Constraint Violations**

Increase Maximum value in HoleSize rule.

![image](https://user-images.githubusercontent.com/1595938/147819740-1a359688-b7bc-4fff-a857-66860713a368.png)

[JLCPCB Capabilities](https://jlcpcb.com/capabilities/Capabilities):
Drill Hole Size: 0.20mm- 6.30mm

**Comment by JoelJaemaa** [comment]
Fixed
