### ISSUE TITLE
Multiple combine operations

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#73]
https://github.com/ut-robotics/picr21-team-tlo-rock/blob/640eadb84083cdc3f1cb29fb544fb14cbe74ae40/robot%20code/game_logic.py#L110-L112

Here you combine rotations determined by the closest ball multiple times. This is expected? Why can it not be done with one combine?

**Comment by peeter-virk** [comment]
Combine takes in only two movements can be changed but not high on the priority list.

**Comment by ReikoR** [comment]
What is the reason for using `rotate_omni` two times in a row?

**Comment by peeter-virk** [comment]
commented the second one out

**Comment by ReikoR** [comment]
What was the purpose of the second line? You should probably delete it, if it's not needed.

**Comment by peeter-virk** [comment]
It was a leftover from some testing I did. Was no longer supposed to be active.
