### ISSUE TITLE
Improve reference designator locations

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#74]
1. Don't place designators on pads or vias:

![image](https://user-images.githubusercontent.com/1595938/147447454-aa1d55c6-a79b-4ba8-bc80-cc78584958ec.png)

2. Put designators close to components:

![image](https://user-images.githubusercontent.com/1595938/147447590-b150024d-f739-4e97-879a-7d53a821e58e.png)

Text can be made smaller, if it's difficult to place the designators.

From JLCPCB capabilites:

Minimum Line Width: 6 mil (0.153mm)
Minimum text height: 40 mil (1.0mm)

https://jlcpcb.com/capabilities/Capabilities

3. Don't overlap designators with other text or lines on silkscreen layer.

![image](https://user-images.githubusercontent.com/1595938/147447807-e565ba16-41f7-467b-b7eb-cfa0728fbc48.png)

![image](https://user-images.githubusercontent.com/1595938/147447893-ea7d6be2-aec0-4276-950f-57d15d188dc6.png)

**Comment by JoelJaemaa** [comment]
Fixed
