### ISSUE TITLE
Use tented vias

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-tlo-rock#75]
Using tented vias might make the soldering a bit easier by helping to avoiding the solder from flowing into vias.

Also might help to avoid shorts when vias are close to different component pads. There does not seem to be any vias like that in the design.

Probably the easiest option to use tented vias, is to create new Solder Mask Expansion rule for vias:

![image](https://user-images.githubusercontent.com/1595938/147448729-3822aa4d-cc87-4501-a4fa-e8aea6120370.png)

Vias under the the driver's are quite big and might make soldering harder even when being tented. It might be better to use small (0.2/0.45) vias, that don't pull away so much solder from the pads.

![image](https://user-images.githubusercontent.com/1595938/147448936-56678f9b-1f08-4ffe-9903-e2cc6f9b6e10.png)

**Comment by JoelJaemaa** [comment]
Added this rule

**Comment by ReikoR** [comment]
Can't see the rule and vias not tented either:

![image](https://user-images.githubusercontent.com/1595938/147850478-72c4a2ea-4539-426a-88e4-804a841d9ea2.png)

**Comment by JoelJaemaa** [comment]
Should be fixed now. Last time Altium crashed while saving and looks like some changes were not saved.
