### ISSUE TITLE
Add fasteners to top and bottom of thrower

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#78]
I suggest adding fasteners to the top of the thrower, else it might bend inwards since nothing is stopping this:
![image](https://user-images.githubusercontent.com/5435954/147870930-8e9247b5-9bfa-4850-ad52-7fab6b24127f.png)

There are also no fastener holes on the bottom.

**Comment by priitro** [comment]
Added fasteners to top an bottom of thrower. 
top
![image](https://user-images.githubusercontent.com/73076712/147925859-c043a5e3-7b36-4a5d-adf0-1865f7468160.png)
bottom
![image](https://user-images.githubusercontent.com/73076712/147925972-c709844f-9ebd-44a5-91ed-85fee24f1279.png)
