### ISSUE TITLE
Add stoppers to top of battery holder

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#79]
I would add a stopper to the top of the holder. Additionally i would remove the bottom tab since it can make it hard to operate:

![image](https://user-images.githubusercontent.com/5435954/147870988-bf0206bf-6d7c-49f3-a55f-659f8d4b832f.png)

**Comment by priitro** [comment]
Removed bottom tab. Now its may be not necessary to add stopper to top? 
![image](https://user-images.githubusercontent.com/73076712/147926636-06c98bbf-7032-46b3-ba2c-91d497d7ccba.png)

**Comment by Akustav** [comment]
Maybe just in case round the corners off, then it is harder to cut into a battery and damage it?

![image](https://user-images.githubusercontent.com/5435954/148637225-3c1e5305-7325-452d-8280-2fb8322677b3.png)

**Comment by priitro** [comment]
Made arc  cut 
![image](https://user-images.githubusercontent.com/73076712/148644528-c4fae856-ba20-41b7-9408-6df6178914e6.png)

**Comment by priitro** [comment]
![image](https://user-images.githubusercontent.com/73076712/148653635-3e47bbea-87fc-46ca-bb71-a8f15b1c738e.png)
