### ISSUE TITLE
USB ports on opposite side of machine

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#80]
Currently the USB exposed USB ports are on the other side of the robot compared to mainboard and camera USB ports. This is by design?

![image](https://user-images.githubusercontent.com/5435954/147871030-75e8ae2c-9fd9-450a-95f0-c0add5bca425.png)

**Comment by priitro** [comment]
Measured cables length and better management and decided stay on that deign. Created one additional hole  for camera cable. And did two slots both side of camera and Nuc stand for fixing cables.
![image](https://user-images.githubusercontent.com/73076712/148580927-e23aece3-1bdc-4a98-aa24-e814a4c536bc.png)
![image](https://user-images.githubusercontent.com/73076712/148580973-8c95d0ca-079c-4b7c-91a9-0901cb47b6fe.png)
