### ISSUE TITLE
Top plate very close to wheel

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#82]
I would increase clearance between t he wheel and top of the chassis:

![image](https://user-images.githubusercontent.com/5435954/147871331-79637c65-e209-4468-9c53-62ebcf11830b.png)

**Comment by priitro** [comment]
Cut off part of top plate now 

![image](https://user-images.githubusercontent.com/73076712/147926139-40af0727-5d39-4e8a-a615-c9495439e9ca.png)
