### ISSUE TITLE
Add ball sensor holders

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#83]
Currently these components are missing.

**Comment by priitro** [comment]
Both holders are now created and added
![image](https://user-images.githubusercontent.com/73076712/148646053-b271aecb-6da0-4377-9e2c-917fe0b7cd34.png)
![image](https://user-images.githubusercontent.com/73076712/148646074-7a6375d3-c900-49f1-91c8-7d9b9332258b.png)
