### ISSUE TITLE
Idea about roller removability

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#85]
If you want the roller to be simple to remove then you can make a cutout to the side that allows you to pull out the whole roller assembly. It removes some supportive material but i think it is usable

![image](https://user-images.githubusercontent.com/5435954/148637544-b8bbad1b-a2f8-431d-9864-b8fd6f5fb0c9.png)

**Comment by priitro** [comment]
Yes its easiest way to remove roller. Hope servo stays in place.
![image](https://user-images.githubusercontent.com/73076712/148644191-36515db6-c952-4c7d-bbfb-cc7ac2ccfd5b.png)
