### ISSUE TITLE
Add some meat to the servo side supportive crossbeam

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#86]
Currently it is quire light on material here. I would add some more material, like this:

![image](https://user-images.githubusercontent.com/5435954/148637575-9326f987-01d6-4f19-b83b-7fb4efd7fda5.png)

**Comment by priitro** [comment]
Added some "meat" 
![image](https://user-images.githubusercontent.com/73076712/148642823-076e1052-80a6-4bb8-ac89-723d0cf7bf82.png)
