### ISSUE TITLE
Interference with servo

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#87]
Currently there is quite some interference between the servo and the side wall:

![image](https://user-images.githubusercontent.com/5435954/148653818-482aadc9-a9d2-4a48-8f69-b16c3442ea56.png)

**Comment by priitro** [comment]
Problem was with pocket - it wasn´t in right measurements and partly cut.  
Now it fits to its pocket.
![image](https://user-images.githubusercontent.com/73076712/148657291-86b440b4-c442-4674-b2f0-11da2f69dd03.png)
