### ISSUE TITLE
Interference in sharp edges on bottom of chassis

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#88]
There is some interference between the thrower ramps and bottom plate:

![image](https://user-images.githubusercontent.com/5435954/148653902-6b9aafd1-bff0-4e8d-9243-8a0bf622eec6.png)

**Comment by priitro** [comment]
Missed that point then mounted thrower. Now corrected.
![image](https://user-images.githubusercontent.com/73076712/148655319-9be63dd3-2f26-4aa9-a461-3e8d707c0659.png)

**Comment by priitro** [comment]
No interferences detected.
![image](https://user-images.githubusercontent.com/73076712/148657367-cdcfac44-89ad-4de2-b700-b2478a8ae93c.png)
