### ISSUE TITLE
Top plate seems difficult to remove

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-tlo-rock#89]
How is the top plate removal planned?
The top plate seems to be unable to move in any direction other than up and down a few mm, and unremovable without removing the thrower or ramps.
![Fusion360_2022-01-09_14-26-33](https://user-images.githubusercontent.com/32770145/148683625-18d3f89a-ff40-4fab-81bb-52aa27f07b44.png)

Because of the battery box, the plate can't be removed at an angle.

One way of insertion would be to extend the cutout, and have the NUC and ramp top bolts removed for the duration of the top plate insertion.
This would also require extending the wires of the power switches and NUC power socket.
![Fusion360_2022-01-09_14-43-35](https://user-images.githubusercontent.com/32770145/148683815-ea76bdb7-c312-47c6-b267-3d67a6e73e04.png)

**Comment by priitro** [comment]
Unfortunately planning that top plate design, the thrower`s ramps height never come to mind. Its not good!


Made following changes in design:
*changed throwers throwing angel from 58 to 65 degrees. It gives 1mm cut off from thrower height, with regular thrower more than 5 mm.
*lifted thrower and ramp middle holding bolt 5mm
*lifted camera 5mm
*lifted NUC  and connectors holes  ca 10 mm
*increased cutoff of the camera and NUC stand 28 mm
Now it gives 5.4 mm space  (10.25-4.8)  for plate insertion and removal.
-unfortunately  ramps upper polts must remove before. 
![image](https://user-images.githubusercontent.com/73076712/148689677-c4e226c3-aa54-4e93-a5ab-91176fa3f6bc.png)

For regular thrower with throwing angle 65 degrees, maybe ramp don't need upper bolts for supporting.
Space for insertion-removal top plate is 14.9 mm (19.7-4.8mm).
![image](https://user-images.githubusercontent.com/73076712/148690114-fffcaf34-f477-4348-bc70-4c0ba375a299.png)
![image](https://user-images.githubusercontent.com/73076712/148690281-db7ffa10-4f6a-4c88-9e44-0e234b8fd0a3.png)

**Comment by priitro** [comment]
If I turned the batteries to a narrower side, the NUC could no longer be switched on. Battery box seen with new dimensions ![image](https://user-images.githubusercontent.com/73076712/149338815-3f18fc7c-5422-4a2a-a961-ab6f624c076d.png)
![image](https://user-images.githubusercontent.com/73076712/149338850-43c0e056-11d7-4268-803e-d24179e32d3b.png)
