### ISSUE TITLE
[Mechanics] - unneeded spacers?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-tlo-rock#9]
What are these spacers used for?

![image](https://user-images.githubusercontent.com/5435954/136435856-bd17a91f-a02f-4191-bd98-42a030c9a35b.png)

**Comment by priitro** [comment]
I didn't found any bolt in suitable measures. I used these that I found and that can use. It's may look ugly but I know its work.
As I understood we have to draw all components and put them in design.

**Comment by priitro** [comment]
Suitable spacer that is 22mm wide is MF.  Same set is used in two other ramp bolt sets.
